### ISSUE TITLE
Documentation about the X,Y layout

### ISSUE THREAD

**Issue by blundell** [pimoroni/inky-phat#10]
You draw the pixels of the InkyPhat here

https://github.com/pimoroni/inky-phat/blob/master/library/inkyphat/inky212x104.py#L206-L215

I was looking for some documentation about how the layout is updated, i.e. what order pixels are drawn, can I reference an individual pixel or does the whole display need refreshing? Can i reference one line of the display etc? Does `partial config` have something to do with it? (is it like a clip) 

Is there any documents or diagrams explaining this? or a datasheet?

_Background, I am trying to port the InkyPhat Python code to Java with AndroidThings_

**Comment by Gadgetoid** [comment]
There's no command to set a single line or pixel, and you partial updates are caveated enough that they're basically worthless: you can only partially update an area as small as 1x8 (this might begin to give you clues about the pixel format) and even then it causes artefacts around the edge of the updated area.

The actual hardware is orientated in portrait; the rows on Inky pHAT are, from the display's perspective, columns and the columns are rows.

In full-display update mode the library sends two 1bit buffers of 2756 bytes- Red and Black. Each byte corresponds to an 8x1 region of the display (in portrait mode) with each bit corresponding to a single pixel. A pixel that is neither Red nor Black is White, and I can't remember which wins if you try to set it to both red *and* black but that should never reasonably happen if you're managing your drawing buffer properly.

You may also notice that Inky pHAT's back buffer is in portrait mode too: https://github.com/pimoroni/inky-phat/blob/master/library/inkyphat/inky212x104.py#L64

And pixel coordinates are translated in `set_pixel`: https://github.com/pimoroni/inky-phat/blob/master/library/inkyphat/inky212x104.py#L221-L223

**Comment by blundell** [comment]
ah great, thanks for that explanation! I'll see what I can come up with from this 👍
