### ISSUE TITLE
How to draw lines in black?

### ISSUE THREAD

**Issue by Kyosfonica** [pimoroni/inky-phat#12]
Hi, 

I am actually using this line to draw a line:
inkyphat.line((31, 15, 184, 15)) 
This draws a white line on the specified coordinates.

Is there a way to be able to change the color? I would like the line to be black.

Thanks.

**Comment by Gadgetoid** [comment]
See: http://pillow.readthedocs.io/en/3.1.x/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.Draw.line

Inky pHAT's drawing methods are based on PIL/Pillow.

```
line(xy, fill=inkyphat.BLACK, width=0)
```
