### ISSUE TITLE
'ImageDraw' object has no attribute 'setfill' with Pillow >= 4.1.0

### ISSUE THREAD

**Issue by DurandA** [pimoroni/inky-phat#2]
When importing inkphat, an AttributeError is triggered:
```
Traceback (most recent call last):
  File "logo.py", line 5, in <module>
    import inkyphat
  File "/usr/local/lib/python3.4/dist-packages/inkyphat/__init__.py", line 29, in <module>
    globals()[method] = getattr(_draw, method)
AttributeError: 'ImageDraw' object has no attribute 'setfill'
```

This is due to `setink()`, `setfill()` and `setfont()` [being deprecated](http://pillow.readthedocs.io/en/4.1.x/releasenotes/4.1.0.html#id1) in Pillow 4.1.0. This is easily fixed by removing references in [`__init__.py` line 28](https://github.com/pimoroni/inky-phat/blob/master/library/inkyphat/__init__.py#L28).

**Comment by Gadgetoid** [comment]
D'oh! And here I thought I was being clever by being selective about which methods I aliased. Clearly wasn't selective enough. Thank you!
