### ISSUE TITLE
error on every example- IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by matteliot** [pimoroni/inky-phat#22]
Maybe you guys could extend the test program/examples to be more diagnostic?
[Found the pinout here]( https://pinout.xyz/pinout/inky_phat)

**~/Pimoroni/inkyphat/examples $ python3 test.py**
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import inkyphat
  File "/usr/local/lib/python3.5/dist-packages/inkyphat/__init__.py", line 24, in <module>
    _panel = inky212x104.Inky212x104(resolution=(HEIGHT, WIDTH), h_flip=False, v_flip=True)
  File "/usr/local/lib/python3.5/dist-packages/inkyphat/inky212x104.py", line 111, in __init__
    self._spi.open(0, self.cs_pin)
**FileNotFoundError: [Errno 2] No such file or directory**

**Comment by Gadgetoid** [comment]
This happens when the SPI bus is not enabled- which is one of the thing the one-line-installer should do automatically. Otherwise, it does mention that SPI is required at the bottom of the README albeit it's not clear. Which install method did you use?

**Comment by matteliot** [comment]
SPI is enabled.   

I first installed via the curl | bash method.  

Then apt-get on python2, then 3.  

All methods gave the same error.

After a clean install, it worked. I had another display on that system before and believe that it might have conflicted.
