### ISSUE TITLE
Change background of the inky phat?

### ISSUE THREAD

**Issue by france193** [pimoroni/inky-phat#26]
How it is possible to change the background of the inky phat?

Where i can find all available Methods of the drawing Library? What is Pillow and Why it is different from PIL? Is it compatibile with inky phat?

Where I can find some more information about the process to write on my inky phat? How it works: Draw on a Canvas, create image and then show image on inky phat...

**Comment by Gadgetoid** [comment]
The Inky pHAT library has been superceded by Inky, which makes it much clearer about how the image creation is accomplished- in short, it just uses the PIL (Python Imaging Library) Library, and basically all of the documentation relating to PIL/Pillow is applicable.

If you're not using a first generation Inky pHAT (dependant upon this library) you should swap to `inky` instead- https://github.com/pimoroni/inky

If you want to set a background, you should start with a `PIL` Image:

```
from PIL import Image

background = Image.open("filename")
```

And then draw over it.

Your image must be palette-based with 3 colours for tri-colour displays, and 2 colours for bi-colour displays.

You can then draw over the top of this `background` using `PIL` and finally display it onto Inky pHAT with `inkyphat.set_image(background)` followed by `inkyphat.show()`.
