### ISSUE TITLE
Yahoo Weather API changed 

### ISSUE THREAD

**Issue by ernesst** [pimoroni/inky-phat#27]
The weather script is now broken has yahoo changed it's api the 3rd of this year.

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired.
> To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service. 

https://developer.yahoo.com/weather/?guccounter=1

**Comment by sandyjmacdonald** [comment]
I believe I've got a fix for this that involves a geocode lookup to get lat/lon coordinates and then scraping the relevant bits of info from https://darksky.net/forecast/. I hope to get it implemented in the morning!

**Comment by mfraser** [comment]
I've rewritten this using OpenWeatherMap at https://github.com/mfraser/weather-phat. My first attempt at fixing this, so it might go wrong.
