### ISSUE TITLE
icalendar

### ISSUE THREAD

**Issue by MrHohenheim** [pimoroni/inky-phat#4]
![123](https://user-images.githubusercontent.com/885044/27984769-414b9c10-63de-11e7-87a4-cfb99b21bc25.png)

pi@raspberrypi:~/Pimoroni/inkyphat/examples $ ./cal-ics.py
Traceback (most recent call last):
  File "./cal-ics.py", line 7, in <module>
    import icalendar
ImportError: No module named icalendar

**Comment by r0ckarong** [comment]
Have you installed the calendar module? 

```pip install icalendar```

**Comment by MrHohenheim** [comment]
oh.. this Works now , i didnt noticed this need install 😊 but now Works…  btw the crontab at the tutorial is not Works becuse   ical  want open background.png and crontab cant handle


Küldte a Windows 10 Posta<https://go.microsoft.com/fwlink/?LinkId=550986>

Feladó: Markus Napp<mailto:notifications@github.com>
Elküldve: 2017. július 8., szombat 20:13
Címzett: pimoroni/inky-phat<mailto:inky-phat@noreply.github.com>
Másolatot kap: PT<mailto:tamas.penzes@hotmail.com>; Author<mailto:author@noreply.github.com>
Tárgy: Re: [pimoroni/inky-phat] icalendar (#4)


Have you installed the calendar module?

pip install icalendar
