### ISSUE TITLE
inkyphat.clear broken

### ISSUE THREAD

**Issue by mnelsoneorm** [pimoroni/inky-phat#5]
Thank you for adding a "clear" function to the library - but it's broken by the little h in hEIGHT:

`

def clear():
--
  | _image.paste(Image.new('P', (WIDTH, hEIGHT)))

`
Luckily "Letter Man" showed up (for anyone old enough to remember that) and changed the little h to a big one and mine is working ; ).

**Comment by Gadgetoid** [comment]
Argh! How the heck did I miss this. *facepalm*

I'll be pushing out a version 0.0.3 possibly next week to address this, and to properly bump the __version__ number than went awry.

Thanks for pointing it out!

**Comment by mnelsoneorm** [comment]
Haha, I've done that one a thousand times....not sure why but pressing the shift key on the first character immediately after pressing the caps lock is somehow hard wired into my brain!
