### ISSUE TITLE
display funkyness after update

### ISSUE THREAD

**Issue by mnelsoneorm** [pimoroni/inky-phat#6]
display no longer looks right after the update.  Looks like the wrong display size was used?

Edit - I just noticed the comment about a possible setting causing dead lines on the display.  That may be what I'm experiencing but wanted to go back to the old library to be sure.  Would it work to just copy the __init__ and ILI9xxx files back and replace the newer ones or is the process more involved than that?  Is there a path to just curl the old one down again?

**Comment by Gadgetoid** [comment]
Grab the .deb files from here: https://github.com/pimoroni/inky-phat/releases/tag/v0.0.1

And install with: `sudo dpkg -i python-inkyphat_0.0.1_all.deb`

That should replace the newer, with the older version.

**Comment by mnelsoneorm** [comment]
Doh, looks like it may be toast.  Even with the old library I still have dead lines.

**Comment by Gadgetoid** [comment]
Zoiks. Please drop us a line to support@pimoroni.com with details of:

1) What Pi you were using it with
2) What examples/code you were running
3) How it was set up, ie: horizontal/vertical
4) How long it took the lines to appear

Sorry for the pop quiz, but details should help us narrow down the cause.

**Comment by asez73** [comment]
Hello, 
I face this problem too and send an email to support.
Hope this is recoverable through software.
Shutting it down, just in case...
